"""add table users

Revision ID: 1e8e7a53600a
Revises: 
Create Date: 2025-10-30 15:07:34.061856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e8e7a53600a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('T_USR_USER',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='genderenum'), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'GUEST', 'LIBRARIAN', name='roleenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_T_USR_USER_email'), 'T_USR_USER', ['email'], unique=True)
    op.create_index(op.f('ix_T_USR_USER_id'), 'T_USR_USER', ['id'], unique=False)
    op.create_index(op.f('ix_T_USR_USER_username'), 'T_USR_USER', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_T_USR_USER_username'), table_name='T_USR_USER')
    op.drop_index(op.f('ix_T_USR_USER_id'), table_name='T_USR_USER')
    op.drop_index(op.f('ix_T_USR_USER_email'), table_name='T_USR_USER')
    op.drop_table('T_USR_USER')
    # ### end Alembic commands ###
